# Bookings made in slots generated by weekly AvailabilityRules have no
# one-off Availability row behind them.
class AllowBookingsWithoutAvailability < ActiveRecord::Migration[8.0]
  def change
    change_column_null :bookings, :availability_id, true
  end
end
