class Booking < ApplicationRecord
  # Set when the slot came from a one-off Availability; nil for slots
  # generated by weekly AvailabilityRules.
  belongs_to :availability, optional: true

  validates :booked_date, presence: true
  validates :start_time, presence: true # end_time comes from the slot
  validates :first_name, presence: true
  validates :email, presence: true,
    format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
  validates :phone_number, presence: true
  validates :confirmation_token, presence: true, uniqueness: true
  validates :status, inclusion: { in: %w[confirmed cancelled completed] }
  validate :not_in_past, on: :create
  validate :in_open_slot, on: :create

  before_validation :generate_confirmation_token, on: :create
  before_validation :normalize_phone_number
  before_validation :take_times_from_slot, on: :create

  scope :confirmed, -> { where(status: "confirmed") }
  scope :cancelled, -> { where(status: "cancelled") }
  scope :completed, -> { where(status: "completed") }
  scope :upcoming, -> { confirmed.where("booked_date > ? OR (booked_date = ? AND start_time > ?)", Date.current, Date.current, Time.current) }
  scope :past, -> { where("booked_date < ? OR (booked_date = ? AND end_time < ?)", Date.current, Date.current, Time.current) }
  scope :for_date, ->(date) { where(booked_date: date) }
  scope :today, -> { where(booked_date: Date.current) }
  scope :this_week, -> { where(booked_date: Date.current.beginning_of_week..Date.current.end_of_week) }
  scope :this_month, -> { where(booked_date: Date.current.beginning_of_month..Date.current.end_of_month) }

  # Creates the booking if its start time is an open slot. Bookings for the
  # same day are serialized with an advisory lock, so two people can't both
  # take the last place in a slot.
  #
  # @return [Booking] persisted, or with errors
  def self.reserve(attributes)
    booking = new(attributes)
    transaction do
      advisory_xact_lock(:booking_slots, booking.booked_date.jd) if booking.booked_date
      booking.save
    end
    booking
  end

  def starts_at
    booked_date.in_time_zone.change(hour: start_time.hour, min: start_time.min)
  end

  def ends_at
    booked_date.in_time_zone.change(hour: end_time.hour, min: end_time.min)
  end

  def cancel!
    transaction do
      update!(status: "cancelled", cancelled_at: Time.current)
    end
  end

  def complete!
    update!(status: "completed")
  end

  def confirmed?
    status == "confirmed"
  end

  def cancelled?
    status == "cancelled"
  end

  def formatted_date
    booked_date.strftime("%A, %B %-d, %Y")
  end

  def formatted_time_range
    "#{start_time.strftime('%l:%M %p').strip} - #{end_time.strftime('%l:%M %p').strip} PST"
  end

  def formatted_date_short
    booked_date.strftime("%B %-d")
  end

  def formatted_start_time
    start_time.strftime("%l:%M %p").strip
  end

  private

  def generate_confirmation_token
    self.confirmation_token ||= SecureRandom.urlsafe_base64(32)
  end

  def normalize_phone_number
    return unless phone_number.present?
    self.phone_number = phone_number.gsub(/[^\d+]/, "")
  end

  # The slot decides the end time and source; anything the client sent for
  # them is ignored.
  def take_times_from_slot
    return unless booked_date && start_time

    @slot = BookingSchedule.new.open_slot(booked_date, start_time.strftime("%H:%M"))
    return unless @slot

    self.end_time = @slot.end_label
    self.availability_id = @slot.availability_id
  end

  def not_in_past
    return unless booked_date.present? && start_time.present?

    errors.add(:base, "Cannot book a time in the past") if starts_at < Time.current
  end

  # Covers times outside every window, misaligned times and full slots.
  def in_open_slot
    return if booked_date.blank? || start_time.blank? || errors[:base].any?

    errors.add(:base, "This time slot is no longer available") unless @slot
  end
end
