# One bookable time on one day, as offered on /book.
#
# availability_id and title are set when the slot comes from a one-off
# Availability; slots generated by weekly AvailabilityRules leave them nil.
BookingSlot = Data.define(:starts_at, :ends_at, :capacity, :availability_id, :title) do
  def date
    starts_at.to_date
  end

  # Wall-clock start ("14:30"), the form bookings store and submit.
  def start_label
    starts_at.strftime("%H:%M")
  end

  def end_label
    ends_at.strftime("%H:%M")
  end
end
